# Server settings
version: 1.0
projectPath:
server:  
    port: 8088
    address: localhost
# SPRING PROFILES
spring:         
    # HTTP ENCODING  
    http:  
        encoding.charset: UTF-8  
        encoding.enable: true  
        encoding.force: true
    mvc:
        prefix: /static/
        suffix: .html
        adminPath: admin
        frontPath: app
        page.pageSize: 20
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/grass?useUnicode=true&characterEncoding=utf-8
        username: root
        password: root
    mybatis:
        typeAliasesPackage: com.grass.module.**.entity
        mapperLocations: classpath:/mapper/module/**.xml
        pageSize: 20
    jpa:
        database: mysql
        show-sql: true
    redis:
        keyPrefix: grass
        host: 127.0.0.1
        port: 6379
        password:
        timeout: 5000
        database: 1
        pool.maxIdle: 300
        pool.maxTotal: 60000
        pool.testOnBorrow: true
shiro:
    session:
      sessionTimeOut: 1800000
      sessionValidationInterval: 120000
      sessionValidationSchedulerEnabled: true
      sessionIdCookieEnabled: true
    cookie:
      name: grass.session.id
    ehcache:
      configFilePath: classpath:ehcache-shiro.xml
    path:
      loginUrl: /login
      successUrl: /success
      map:
        ${spring.mvc.adminPath}/a: authc
        ${spring.mvc.adminPath}/b: anon
        ${spring.mvc.adminPath}/c: user
