# Server settings
version: 1.0
projectPath:
server:  
    port: 8088
    address: localhost


# SPRING PROFILES
spring:
    # HTTP ENCODING
    http:
        encoding.charset: UTF-8
        encoding.enable: true
        encoding.force: true
    mvc:
        prefix: /static/
        suffix: .html
        adminPath: admin
        frontPath: app
        page.pageSize: 20
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/grass?useUnicode=true&characterEncoding=utf-8
        username: root
        password: root
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    mybatis:
        typeAliasesPackage: com.grass.module
        mapperLocations: classpath:/mapper/**/*.xml
        pageSize: 20
    jpa:
        database: mysql
        show-sql: true
    redis:
        keyPrefix: grass
        hostName: 127.0.0.1
        port: 6379
        password:
        timeout: 5000
        database: 1
        enableTransactionSupport: true
        pool.maxIdle: 300
        pool.maxTotal: 60000
        pool.testOnBorrow: true


#shiro settings
shiro:
    session:
        sessionTimeOut: 1800000
        sessionValidationInterval: 120000
        sessionValidationSchedulerEnabled: true
        sessionIdCookieEnabled: true
    cookie:
        name: grass.session.id
    ehcache:
        configFilePath: classpath:ehcache-shiro.xml
    path:
        loginUrl: /
        successUrl: /success
        failureUrl: /
        map:
            /admin/user/**: user
            /admin: authc
            /admin/th: anon
            /login: anon

    cas:
        casServerUrlPrefix: https://localhost:8443/cas
        casLoginUrl: https://localhost:8443/cas/login
        casLogoutUrl: https://localhost:8443/cas/logout
        shiroServerUrlPrefix: http://localhost:8088
        casFilterUrlPattern: /shiro-cas
        loginUrl: https://localhost:8443/cas/login?service=http://localhost:8088/shiro-cas
